### ISSUE TITLE
how to run this project ??

### ISSUE THREAD

**Issue by vTNT** [bepetersn/flask-permissions-ex#1]
how to create all table??

**Comment by bepetersn** [comment]
Thanks for the question! See the new README. To create tables, you can do `./manage.py db init`. There's not a lot to this project, but if you want to test it out you can do `./manage.py shell` to play with the db tables the project provides.

**Comment by vTNT** [comment]
i already read the readme before i run this project.   and then i edit the config.py;   i run ./manage.py shell, but I met this mistake
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 839, in _join_condition
    (a.description, b.description, hint))
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'fp_user' and 'user'.

soI will consult how to run this project

**Comment by vTNT** [comment]
thank u:)
